development:
  sessions:
    default:
      database: revveries_dev
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

test:
  sessions:
    default:
      database: revveries_test
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
  options:
    identity_map_enabled: true
