development:
  sessions:
    default:
      database: revveries_dev
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

test:
  sessions:
    default:
      database: revveries_test
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

production:
  sessions:
    default:
      database: <%= ENV['MONGO_DB'] %>
      hosts:
        - <%= ENV['MONGO_HOST'] %>
      username: <%= ENV['MONGO_USER'] %>
      password: <%= ENV['MONGO_PASS'] %>
  options:
    identity_map_enabled: true
